name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
            - name: Setup SDL
  # You may pin to the exact commit or the version.
  # uses: libsdl-org/setup-sdl@0b4058be1a69a43f9875e9a17f41e636495f5852
  uses: libsdl-org/setup-sdl@v1
  with:
    # Required version of SDL (2.x.y, 2-any, 2-latest, 2-head, 3-head), or git hash
    version: # default is 2-any
    # Version of SDL_image (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
    version-sdl-image: # optional
    # Version of SDL_mixer (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
    version-sdl-mixer: # optional
    # Version of SDL_net (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
    version-sdl-net: # optional
    # Version of SDL_rtf (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
    version-sdl-rtf: # optional
    # Version of SDL_ttf (2.x.y, 2-any, 2-latest, 2-head, 3-head), git hash, or <empty>
    version-sdl-ttf: # optional
    # Allow pre-releases
    pre-release: # default is true
    # CMake build type (Release/Debug/RelWithDebInfo/MinSizeRel)
    build-type: # default is Debug
    # Build and install SDL_test library
    sdl-test: # optional, default is false
    # Path of a CMake toolchain file
    cmake-toolchain-file: # optional
    # CMake generator name (see https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html)
    cmake-generator: # optional
    # Extra CMake arguments during configuration
    cmake-arguments: # optional
    # Install dependencies (supports apt-get, dnf, brew, and msys2-pacman)
    install-linux-dependencies: # optional
    # Run commands as `$shell $file` (with $file containing the build commands)
    shell: # optional
    # Unique string to include in the GitHub SDL cache hash
    discriminator: # optional
    # Add path of the SDL (shared) library to PATH/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH
    add-to-environment: # optional, default is false
    # A GitHub API token.
    token: # optional, default is ${{ github.token }}
          
